introspection/parse.go

fix issue: modelgen generates code for member of unions which not implement union types interface

fix unions

---

clientgen/client.go
clientgen/source.go
clientgen/source_generator.go
clientgen/template.go
clientgen/template.gotpl

Don't generate Query and Mutation type struct by gqlgen. It is correct because it's server lib. But gqlgenc is a client lib. So gqlgenc need Query and Mutation struct. 
For example, [Shopify Admin API](https://shopify.dev/docs/admin-api) use Query in [the Job](https://shopify.dev/docs/admin-api/graphql/reference/object/job).

Generate Query and Mutation struct

---

client/client.go
client/client_test.go
example/github/main.go
go.mod
go.sum
graphqljson/graphql.go

This PR implements my vision for the error handling of a graphql response (when possible), inspired by apollo client.
Basically an operation can fail for 3 possible reasons:
1. network: when the server returns a "non OK" http code 
2. graphql: when the request is bad formatted for instance, 200 is returned and the error is described in the response
3. everything else: http code 200 but server returned data with a bad format, failed to perform the request, and so on
Network and graphql errors can be handled in a struct like the following, they both implements the go error interface
```go
import "github.com/vektah/gqlparser/v2/gqlerror"
type HTTPError struct {
Code    int    `json:"code"`
Message string `json:"message"`
}
type ErrorResponse struct {
// populated when http status code is not …
```

error handling implementation

---

client/client_test.go
config/config.go
config/config_test.go
graphqljson/graphql_test.go
main.go

Now, Don't generate for `go generate`. the following code  join gqlgenc.
source: https://github.com/99designs/gqlgen/blob/862762c77bae8b5f119c401d037358cfaf33fa52/codegen/config/config.go#L71-L84

Fixed to load config file like gqlgen

---

README.md

Currently, these are the valid filenames:
This updates the documentation so the readme uses one of them

Use valid gqlgenc file in readme

---

clientgen/template.gotpl
clientgenv2/template.gotpl

The `Query` suffix is not ideal in my opinion since:
- It's weird to use `Query` suffix when the actual document type is a Mutation, and gives weird usage like `updateUser(gql.UpdateUserQuery)`.
- A Query naming suffix in the generate config is something that could prove to be wanted, lead to confusion with the "document"
A such, I propose to change the suffix from `Query` to `Op`. I thought about using `Document`
or `Doc` but `Op` felt more aligned with the fact that we range over a list of operations.
This can be seen as a backward breaking change since upon a re-run of the gqlgenc binary,
some variables will not have the same name.
Alternatives:
- Keep `Query` as the default suffix but allow a rename through the `GenerateConfig` object.
- Perform the necessary change but generate also …

Proposition to change the generated document variable's name suffix to `Document` instead of `Query`

---

client/client.go

Fixes: https://github.com/Yamashou/gqlgenc/issues/109
This PR prevents the situation when the Header "Content-Type" for  `type HTTPRequestOption func(req *http.Request)` function   is overwritten. I have implemented my own HTTPRequestOption function where I set it for `multipart/form-data; boundary=` to be able to upload files but finally, the req Header was different.

prevent overwrite Header by HTTPRequestOption function

---

graphqljson/graphql.go
graphqljson/graphql_test.go

Currently, there is no support for a schema with `map[string]interface{}`. This PR extends the decode method to unmarshal the map type. 
It was the main reason why I opened the previous issue: #141
All tests are passing right now

add map support for json parser

---

clientgenv2/query.go

Ive been using gqlgenc a lot recently, and I have noticed that for queries/mutations that use several fragments, each time I run `gqlgenc`, the order of the fragments in the operation document string change order. This causes generation to not be deterministic for me. For operations with only a couple of fragments, generation seemed to be deterministic. 
I had a look at the source code and discovered in the `fragmentsUnique` function, a map of unique fragments was being created and then the map was used to create a slice of those unique fragments. This explains why my fragments were changing order. To fix it have have modified the way you create the slice of unique fragments to ensure the order is deterministic.
This change would be very helpful to me so i can run `gqlgenc` multiple …

Fix indeterministic fragment order in operation document string

---

README.md
config/config.go
go.mod
go.sum
main.go

I prefer to keep a root directory of my project clean and want to be able to specify a directory where to load .gqlgenc.yml file from.
You can still run
```
gqlgenc
```
without any arguments to apply a current behavior of loading .gqlgenc.yml from a current directory, or you can specify the exact location of the .gqlgenc.yml file, by running app such as
```
gqlgenc generate --configdir ./schemas
```
in this case .gqlgenc.yml will be loaded from a ./schemas directory in current folder
I have added urfave dependency into "gqlgenc" project, but main "gqlgen" project also uses it.

optionally specify directory to load .gqlgenc.yml from

---

README.md

This PR just does:
- Fix a full-width space in the example YAML in README
- Bonus: Remove trailing spaces in README

Fix a full-width space in README

---

main.go

This adds newline to all error statements in order to easily read error messages.
All error statements are lack of newline, so I added newline in main.go.

add newline to error statement

---

clientgenv2/client.go

- Prevent a panic in case of the schema does not have any Query or Mutation
The current `gqlgenc` causes a panic like the one below when the target GraphQL schema does not have Query or Mutation. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x916a39]
goroutine 1 [running]:
github.com/Yamashou/gqlgenc/clientgenv2.(*SourceGenerator).NewResponseFieldsByDefinition(0xc004057840, 0x0)
/path/to/go/pkg/mod/github.com/!yamashou/gqlgenc@v0.13.5/clientgenv2/source_generator.go:107 +0x39
```
If I understand correctly, a GraphQL schema that does not have Query or Mutation is valid. In my case, I want to use `gqlgenc` with the GraphQL schema that does not have any Mutation.

Prevent a panic in case of the schema does not have any Query or Mutation

---

clientgenv2/template.gotpl

- When ParseDataWhenErrors is set to true, the function will return not only errors but also data field by res variable.
```
ParseDataWhenErrors: true
```
In the current version of gqlgenc, even if ParseDataWhenErrors is set to true, only err is returned, making it impossible to compare the data field in tests. It's likely that users who set ParseDataWhenErrors to true also want to compare res at the same time.

Returan data when errors

---

README.md

The client/clientgen(v1) has already been removed.
Updated README to use the clientv2/clientgenv2.

update README to use clientv2 by default

---

clientv2/client_test.go

Adds a test for https://github.com/Yamashou/gqlgenc/issues/219
On version `v0.21.2`:
```
=== RUN   TestMarshalJSON/marshal_nested
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0x140201e0380 stack=[0x140201e0000, 0x140401e0000]
fatal error: stack overflow
```
On latest: 
```
--- PASS: TestMarshalJSON/marshal_NumberOne (0.00s)
--- PASS: TestMarshalJSON/marshal_NumberTwo (0.00s)
--- PASS: TestMarshalJSON/marshal_nested (0.00s)
--- PASS: TestMarshalJSON/marshal_a_struct_with_custom_marshaler (0.00s)
--- PASS: TestMarshalJSON/marshal_map_with_custom_marshaler (0.00s)
--- PASS: TestMarshalJSON/marshal_time.Time (0.00s)
--- PASS: TestMarshalJSON/marshal_time.Time#01 (0.00s)
PASS
ok  	github.com/Yamashou/gqlgenc/clientv2	0.140s
```

Add test case for nested structs

---

clientgenv2/source_generator.go
config/config.go
config/generate_config.go

When updating to a more recent version of `gqlgenc`, we encountered issues with the generation of models for non-null fields. Non-null structs fields are always pointers instead of being defined as values. We were impacted by the following two changes:
- Match gqlgen default settings: #202
- struct type field for fragment is pointer: https://github.com/Yamashou/gqlgenc/pull/104/commits/2bb5b94f1784f7dc1cbd8aee7228ff226192457e. This one is quite old, but that change was in only done in client v2, and we were still using client v1.
This PR is to make the generation of non-null structs fields as pointers configurable. 
I've used the same name used by `gqlgen` for the similar config: `struct_fields_always_pointers`. Unfortunately, that name doesn't fit well with other settings like …

Make gqlgen StructFieldsAlwaysPointers configurable

---

main.go

Version in main.go is still set at 0.21.1. This PR bumps the version to 0.22.1.  Can we get a release of 0.22.1 with just the version change?

Update version in main.go to 0.22.1

---

clientv2/client.go
clientv2/client_test.go

- **fix**
- **fix**
- **back**
- **fix**
- **fix**
- **delete test struct**

Request MarshalGQL

---

clientv2/client.go
clientv2/client_test.go
go.mod

I would like to use a type provided by 3rd party package. When the type does not implement neither graphql.Marshaler nor json.Marshaler, the result of MarshalJSON generates an unexpected string in some cases.
For example, assuming using github.com/google/uuid.uuid.UUID in a variable,
This is an example schema.
```
type Query {
uuidToString(uuid: UUID!): String!
}
scalar UUID
```
Bind the scalar to in gqlgenc.yaml
```
models:
UUID:
model: github.com/google/uuid.UUID
```
Then, gqlgenc generates a code to marshal a variable like this:
```go
vars := map[string]any{
"uuid":   uuid.New(),
}
b, err := clientv2.MarshalJSON(vars)
...
fmt.Printf("json: %s\n", b)
```
This generates a json value,
```
json: {"uuid":[173,99,127,52,45,165,69,156,136,157,99,98,166,115,160,109]} // unexpected
```
However, …

use encoding.TextMarshaler if a value implements it

---

.github/workflows/go.yml
.golangci.yml
clientgenv2/source_generator.go
clientgenv2/template.go
clientv2/client.go
generator/generator.go
go.mod
go.sum
graphqljson/graphql.go
introspection/parse.go

- bumps `github.com/99designs/gqlgen v0.17.54` 
- there was another breaking change to the function signature in `gqglen`, this time for `federation.New()` now requires the gqlgen config to be passed in and returns the `Federation` and error. I updated this [here](https://github.com/Yamashou/gqlgenc/compare/master...golanglemonade:gqlgenc:federation-gqlgen-breaking-change?expand=1#diff-ebe0c9061541da82c4de858d4996649ee6d33bf4036cb96200cc3f3ae891a536R65-R75).
- I also noticed when running the linter that it was failing to run at least locally because of a large number of warnings due to deprecated linters. I removed those from the `disable` and updated the failing linter errors (mostly around using `range` after go1.22). 
-  updates the linter version in actions to the latest version …

update for gqlgen 0.17.54 federation change

---

clientgenv2/template.gotpl
clientv2/client.go

Having HTTP Client as an interface allows us to use more complex http client implementations. The one I am personally interested at is [github.com/sethgrid/pester](https://github.com/sethgrid/pester) which allows us to use resilient  requests to remote GraphQL server by implementing a retry strategy on underlying HTTP requests.
The rest of the repository requires no change. All the existing generated code will be compatible with the proposed change.
Example:
```
package ein
import (
"context"
"net/http"
"time"
"github.com/sethgrid/pester"
"github.com/Yamashou/gqlgenc/clientv2"
)
func NewEinHttpClientWithRetry(roundTripper http.RoundTripper) clientv2.HttpClient {
client := pester.New()
client.Transport = roundTripper
client.Timeout = 120 * time.Second
client.Concurrency = 1 …
```

HTTP Client as an interface

---

config/config.go
go.mod

Updates `yaml.v2` -> `yaml.v3`.
See https://github.com/go-yaml/yaml/issues/602 for details on the `UnmarshalStrict` change.

upgrade gopkg.in/yaml.v2 -> v3

---

clientgenv2/source_generator.go
clientv2/client.go
clientv2/client_test.go

Add UnsafeChainInterceptor

---

querydocument/query_document.go

The processedType Map is not updated when there is a cycle in the type definitions and causes an infinite recursion. Updating the processedType Map before the cycle should solve the issue.
Co-authored-by: Jonathan Kohlhas <JonathanKohlhas@users.noreply.github.com>

fix: infinite recursion in inputObject

---

config/generate_config.go
example/autobind/schema/schema.graphql
main.go

Updated the conditional logic to return true when no value is specified for EnableClientJsonOmitemptyTag.
```go
func (c *GenerateConfig) IsEnableClientJsonOmitemptyTag() bool {
if c == nil {
return true
}
if c.EnableClientJsonOmitemptyTag == nil {
return true
}
return *c.EnableClientJsonOmitemptyTag
}
```
This ensures that the default behavior remains consistent and returns true when the configuration is not explicitly set.

Fix Conditional Logic for `OmitemptyTag`

---

clientgenv2/template.go

The upstream changes to `any` were causing a `map[string]any` to be converted to:
```
map[string]*Type.Alias----
```
This should resolve it by getting the underly type of the alias.

fix type.Alias for any fields

---

clientgenv2/source_generator.go

Fragment pattern support is now enabled in #254. 
However, if multiple fragments share the same name field, it causes a crash. 
I've fixed that issue.

Fix generator for multiple fragment pattern

---

go.mod

- use go 1.23.8
- setting it to 1.24.2 force everyone to use this version at least
Reference: https://go.dev/ref/mod#go-mod-file-go

leave go to its minimal required version from dependencies

---

main.go

This makes overriding possible for packaging in case the version number is not up to date.
Related to: https://github.com/NixOS/nixpkgs/pull/398878

fix: make version a var
